<?php

/**
 * @file
 * Views Data Export module hook implementations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function views_data_export_form_views_ui_edit_display_form_alter(array &$form, FormStateInterface $form_state) {
  $storage = $form_state->getStorage();
  $display = $storage['view']->getDisplay($storage['display_id']);

  // Only display this on REST export settings forms.
  if ($display['display_plugin'] !== 'rest_export' || $storage['type'] !== 'style_options') {
    return;
  }

  $csv_settings_defaults = $display['display_options']['style']['options']['csv_settings'];

  $form['options']['style_options']['csv_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('CSV Settings'),
    '#states' => array(
      'visible' => array(':input[name="style_options[formats][csv]"]' => array('checked' => TRUE)),
    ),
    'delimiter' => array(
      '#type' => 'textfield',
      '#title' => t('Delimiter'),
      '#description' => t('Indicates the character used to delimit fields. Defaults to a comma (<code>,</code>). For tab-separation use <code>\t</code> characters.'),
      '#default_value' => !empty($csv_settings_defaults['delimiter']) ? $csv_settings_defaults['delimiter'] : ',',
    ),
    'enclosure' => array(
      '#type' => 'textfield',
      '#title' => t('Ensclosure'),
      '#description' => t('Indicates the character used for field enclosure. Defaults to a double quote (<code>"</code>).'),
      '#default_value' => !empty($csv_settings_defaults['enclosure']) ? $csv_settings_defaults['enclosure'] : '"',
    ),
    'escape_char' => array(
      '#type' => 'textfield',
      '#title' => t('Escape Character'),
      '#description' => t('Indicates the character used for escaping. Defaults to a backslash (<code>\</code>).'),
      '#default_value' => !empty($csv_settings_defaults['escape_char']) ? $csv_settings_defaults['escape_char'] : '\\',
    ),
    'strip_tags' => array(
      '#type' => 'checkbox',
      '#title' => t('Strip HTML'),
      '#description' => t('Strips HTML tags from CSV cell values.'),
      '#default_value' => !empty($csv_settings_defaults['strip_tags']) ? $csv_settings_defaults['strip_tags'] : TRUE,
    ),
    'trim' => array(
      '#type' => 'checkbox',
      '#title' => t('Trim Whitespace'),
      '#description' => t('Trims whitespace from beginning and end of CSV cell values.'),
      '#default_value' => !empty($csv_settings_defaults['trim']) ? $csv_settings_defaults['trim'] : TRUE,
    ),
    'encoding' => array(
      '#type' => 'radios',
      '#title' => t('Encoding'),
      '#description' => t('Determines the encoding used for CSV cell values.'),
      '#options' => array(
        'utf8' => t('UTF-8'),
      ),
      '#default_value' => !empty($csv_settings_defaults['encoding']) ? $csv_settings_defaults['encoding'] : 'utf8',
    ),
  );
}
